package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caminhao generated by hbm2java
 */
@Entity
@Table(name="caminhao"
    ,schema="public"
)
public class Caminhao  implements java.io.Serializable {


     private int idcaminhao;
     private String marca;
     private String modelo;
     private int ano;
     private int carga;
     private String placa;
     private int capacidade;
     private Set usuarios = new HashSet(0);
     private Set cargas = new HashSet(0);

    public Caminhao() {
    }

	
    public Caminhao(int idcaminhao, String marca, String modelo, int ano, int carga, String placa, int capacidade) {
        this.idcaminhao = idcaminhao;
        this.marca = marca;
        this.modelo = modelo;
        this.ano = ano;
        this.carga = carga;
        this.placa = placa;
        this.capacidade = capacidade;
    }
    public Caminhao(int idcaminhao, String marca, String modelo, int ano, int carga, String placa, int capacidade, Set usuarios, Set cargas) {
       this.idcaminhao = idcaminhao;
       this.marca = marca;
       this.modelo = modelo;
       this.ano = ano;
       this.carga = carga;
       this.placa = placa;
       this.capacidade = capacidade;
       this.usuarios = usuarios;
       this.cargas = cargas;
    }
   
     @Id 

    
    @Column(name="idcaminhao", unique=true, nullable=false)
    public int getIdcaminhao() {
        return this.idcaminhao;
    }
    
    public void setIdcaminhao(int idcaminhao) {
        this.idcaminhao = idcaminhao;
    }

    
    @Column(name="marca", nullable=false, length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", nullable=false, length=45)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="ano", nullable=false)
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }

    
    @Column(name="carga", nullable=false)
    public int getCarga() {
        return this.carga;
    }
    
    public void setCarga(int carga) {
        this.carga = carga;
    }

    
    @Column(name="placa", nullable=false, length=45)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="capacidade", nullable=false)
    public int getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(int capacidade) {
        this.capacidade = capacidade;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="caminhaos")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="caminhao")
    public Set getCargas() {
        return this.cargas;
    }
    
    public void setCargas(Set cargas) {
        this.cargas = cargas;
    }




}


