package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carga generated by hbm2java
 */
@Entity
@Table(name="carga"
    ,schema="public"
)
public class Carga  implements java.io.Serializable {


     private int idcarga;
     private Caminhao caminhao;
     private Endereco endereco;
     private Pedido pedido;
     private Date data;
     private String nf;

    public Carga() {
    }

    public Carga(int idcarga, Caminhao caminhao, Endereco endereco, Pedido pedido, Date data, String nf) {
       this.idcarga = idcarga;
       this.caminhao = caminhao;
       this.endereco = endereco;
       this.pedido = pedido;
       this.data = data;
       this.nf = nf;
    }
   
     @Id 

    
    @Column(name="idcarga", unique=true, nullable=false)
    public int getIdcarga() {
        return this.idcarga;
    }
    
    public void setIdcarga(int idcarga) {
        this.idcarga = idcarga;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcaminhao", nullable=false)
    public Caminhao getCaminhao() {
        return this.caminhao;
    }
    
    public void setCaminhao(Caminhao caminhao) {
        this.caminhao = caminhao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idendereco", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpedido", nullable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=13)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="nf", nullable=false, length=45)
    public String getNf() {
        return this.nf;
    }
    
    public void setNf(String nf) {
        this.nf = nf;
    }




}


