package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,schema="public"
)
public class Cidade  implements java.io.Serializable {


     private int idcidade;
     private Estado estado;
     private String nome;
     private Set ruas = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int idcidade, Estado estado, String nome) {
        this.idcidade = idcidade;
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(int idcidade, Estado estado, String nome, Set ruas) {
       this.idcidade = idcidade;
       this.estado = estado;
       this.nome = nome;
       this.ruas = ruas;
    }
   
     @Id 

    
    @Column(name="idcidade", unique=true, nullable=false)
    public int getIdcidade() {
        return this.idcidade;
    }
    
    public void setIdcidade(int idcidade) {
        this.idcidade = idcidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getRuas() {
        return this.ruas;
    }
    
    public void setRuas(Set ruas) {
        this.ruas = ruas;
    }




}


