package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,schema="public"
)
public class Endereco  implements java.io.Serializable {


     private int idendereco;
     private Rua rua;
     private int numero;
     private String bairro;
     private String cep;
     private Set cargas = new HashSet(0);
     private Set pessoas = new HashSet(0);

    public Endereco() {
    }

	
    public Endereco(int idendereco, Rua rua, int numero, String bairro, String cep) {
        this.idendereco = idendereco;
        this.rua = rua;
        this.numero = numero;
        this.bairro = bairro;
        this.cep = cep;
    }
    public Endereco(int idendereco, Rua rua, int numero, String bairro, String cep, Set cargas, Set pessoas) {
       this.idendereco = idendereco;
       this.rua = rua;
       this.numero = numero;
       this.bairro = bairro;
       this.cep = cep;
       this.cargas = cargas;
       this.pessoas = pessoas;
    }
   
     @Id 

    
    @Column(name="idendereco", unique=true, nullable=false)
    public int getIdendereco() {
        return this.idendereco;
    }
    
    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idrua", nullable=false)
    public Rua getRua() {
        return this.rua;
    }
    
    public void setRua(Rua rua) {
        this.rua = rua;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", nullable=false, length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cep", nullable=false, length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="endereco")
    public Set getCargas() {
        return this.cargas;
    }
    
    public void setCargas(Set cargas) {
        this.cargas = cargas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="endereco")
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


