package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,schema="public"
)
public class Estado  implements java.io.Serializable {


     private int idestado;
     private String nome;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idestado, String nome) {
        this.idestado = idestado;
        this.nome = nome;
    }
    public Estado(int idestado, String nome, Set cidades) {
       this.idestado = idestado;
       this.nome = nome;
       this.cidades = cidades;
    }
   
     @Id 

    
    @Column(name="idestado", unique=true, nullable=false)
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


