package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rua generated by hbm2java
 */
@Entity
@Table(name="rua"
    ,schema="public"
)
public class Rua  implements java.io.Serializable {


     private int idrua;
     private Cidade cidade;
     private String nome;
     private Set enderecos = new HashSet(0);

    public Rua() {
    }

	
    public Rua(int idrua, Cidade cidade, String nome) {
        this.idrua = idrua;
        this.cidade = cidade;
        this.nome = nome;
    }
    public Rua(int idrua, Cidade cidade, String nome, Set enderecos) {
       this.idrua = idrua;
       this.cidade = cidade;
       this.nome = nome;
       this.enderecos = enderecos;
    }
   
     @Id 

    
    @Column(name="idrua", unique=true, nullable=false)
    public int getIdrua() {
        return this.idrua;
    }
    
    public void setIdrua(int idrua) {
        this.idrua = idrua;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcidade", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rua")
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


