package entidade;
// Generated 24/08/2017 20:31:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Permissoes permissoes;
     private Pessoa pessoa;
     private String usuario;
     private String senha;
     private String cargo;
     private boolean situacao;
     private Set pedidos = new HashSet(0);
     private Set caminhaos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, Permissoes permissoes, Pessoa pessoa, String usuario, String senha, String cargo, boolean situacao) {
        this.idusuario = idusuario;
        this.permissoes = permissoes;
        this.pessoa = pessoa;
        this.usuario = usuario;
        this.senha = senha;
        this.cargo = cargo;
        this.situacao = situacao;
    }
    public Usuario(int idusuario, Permissoes permissoes, Pessoa pessoa, String usuario, String senha, String cargo, boolean situacao, Set pedidos, Set caminhaos) {
       this.idusuario = idusuario;
       this.permissoes = permissoes;
       this.pessoa = pessoa;
       this.usuario = usuario;
       this.senha = senha;
       this.cargo = cargo;
       this.situacao = situacao;
       this.pedidos = pedidos;
       this.caminhaos = caminhaos;
    }
   
     @Id 

    
    @Column(name="idusuario", unique=true, nullable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpermissoes", nullable=false)
    public Permissoes getPermissoes() {
        return this.permissoes;
    }
    
    public void setPermissoes(Permissoes permissoes) {
        this.permissoes = permissoes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpessoa", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="senha", nullable=false, length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="cargo", nullable=false, length=45)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="situacao", nullable=false)
    public boolean isSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(boolean situacao) {
        this.situacao = situacao;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuario_pedido", schema="public", joinColumns = { 
        @JoinColumn(name="idusuario", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idpedido", nullable=false, updatable=false) })
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuario_caminhao", schema="public", joinColumns = { 
        @JoinColumn(name="idusuario", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idcaminhao", nullable=false, updatable=false) })
    public Set getCaminhaos() {
        return this.caminhaos;
    }
    
    public void setCaminhaos(Set caminhaos) {
        this.caminhaos = caminhaos;
    }




}


